# Generated by Django 3.1.5 on 2021-05-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=100)),
                ('previous_hash', models.CharField(max_length=60)),
                ('nonce', models.TextField()),
                ('transactions', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='owned_coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_public_key_p1', models.CharField(max_length=1000)),
                ('owner_public_key_p2', models.CharField(max_length=10)),
                ('hash', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=10)),
                ('signature', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='unspent_coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_public_key_p1', models.CharField(max_length=1000)),
                ('owner_public_key_p2', models.CharField(max_length=10)),
                ('hash', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=10)),
                ('signature', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
