# Generated by Django 3.1.5 on 2021-05-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eggcoin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blockchain',
            new_name='Block_chain',
        ),
    ]
